name: test

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir gettext
      # 4194304 / 2048 = 2048 (MebiByte)
      - run: diskutil partitionDisk $(hdiutil attach -nomount ram://4194304) 1 GPTFormat APFS 'ramdisk' '100%'
      - run: diskutil info /Volumes/ramdisk
      - run: diskutil mount -mountPoint gettext /dev/disk1s2
      - run: curl -fsSLO https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.xz
        working-directory: gettext
      - run: tar fvx gettext-0.21.tar.xz
        working-directory: gettext
      - run: >
          ./configure
          --prefix=$(pwd)/gettext
          --enable-option-checking
          --disable-dependency-tracking
          --disable-java
          --disable-csharp
          --disable-largefile
          --enable-fast-install
          --disable-c++
          --enable-cross-guesses
          --enable-relocatable
          --without-emacs
          --without-lispdir
          --without-git
          --without-cvs
          --without-bzip2
          --without-xz
        working-directory: gettext/gettext-0.21
      - run: make
        working-directory: gettext/gettext-0.21
      - run: make install
        working-directory: gettext/gettext-0.21
